// Generated by CoffeeScript 1.6.3
(function() {
  var cache, fs, http, mime, path, send404, sendFile, serveStatic, server;

  http = require('http');

  fs = require('fs');

  path = require('path');

  mime = require('mime');

  cache = {};

  send404 = function(response) {
    response.writeHead(404, {
      'Content-Type': 'text/plain'
    });
    response.write('Error 404: resource not found.');
    return response.end();
  };

  sendFile = function(response, filePath, fileContents) {
    response.writeHead(200, {
      'content-type': mime.lookup(path.basename(filePath))
    });
    return response.end(fileContents);
  };

  serveStatic = function(response, cache, absPath) {
    if (cache[absPath]) {
      return sendFile(response, absPath, cache[absPath]);
    } else {
      return fs.exists(absPath, function(exists) {
        if (exists) {
          return fs.readFile(absPath, function(err, data) {
            if (err) {
              return send404(response);
            } else {
              cache[absPath] = data;
              return sendFile(response, absPath, data);
            }
          });
        } else {
          return send404(response);
        }
      });
    }
  };

  server = http.createServer(function(request, response) {
    var absPath, filePath;
    filePath = false;
    filePath = request.url === '/' ? 'public/index.html' : "public" + request.url;
    absPath = "./" + filePath;
    return serveStatic(response, cache, absPath);
  });

  server.listen(3000, function() {
    return console.log('Server listening on port 3000.');
  });

}).call(this);
